import os
import datetime
import logging
from pathlib import Path

from fpdf import FPDF
from models import db, Scan, Vulnerability, VM

logger = logging.getLogger(__name__)


class ScanReportPDF(FPDF):
    COLORS = {
        'primary':  (0, 145, 234),
        'accent':   (0, 229, 255),
        'critical': (255, 71, 71),
        'high':     (255, 152, 0),
        'medium':   (255, 211, 61),
        'low':      (81, 207, 102),
        'text':     (50, 50, 50),
        'muted':    (100, 100, 100),
        'gray':     (128, 128, 128),
        'white':    (255, 255, 255),
        'dark':     (30, 30, 30),
    }

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        self.set_author('Aegis Security Platform')

    def set_color(self, name: str):
        color = self.COLORS.get(name, (50, 50, 50))
        self.set_text_color(*color)

    def header(self):
        self.set_font('Arial', 'B', 16)
        self.set_color('primary')
        self.cell(0, 10, 'Aegis Security Platform', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.set_color('muted')
        self.cell(0, 5, 'Vulnerability Scan Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_color('gray')
        self.cell(0, 10,
            f'Page {self.page_no()} | Generated by Aegis Security Platform | '
            f'{datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}',
            0, 0, 'C'
        )

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 14)
        self.set_color('primary')
        self.cell(0, 10, title, 0, 1, 'L')
        self.ln(2)

    def section_title(self, title):
        self.set_font('Arial', 'B', 12)
        self.set_text_color(0, 0, 0)
        self.cell(0, 8, title, 0, 1, 'L')
        self.ln(1)

    def body_text(self, text):
        self.set_font('Arial', '', 11)
        self.set_color('text')
        self.multi_cell(0, 6, text)
        self.ln(2)

    def stat_row(self, label, value, color='text'):
        self.set_font('Arial', 'B', 10)
        self.set_color('muted')
        self.cell(60, 7, label, 0, 0)
        self.set_font('Arial', '', 10)
        self.set_color(color)
        self.cell(0, 7, str(value), 0, 1)

    def severity_badge(self, severity: str):
        """Draw a colored severity badge inline."""
        color_map = {
            'critical': 'critical',
            'high':     'high',
            'medium':   'medium',
            'low':      'low',
        }
        color_name = color_map.get((severity or 'low').lower(), 'low')
        self.set_font('Arial', 'B', 9)
        self.set_color(color_name)
        self.cell(30, 5, severity.upper() if severity else 'UNKNOWN', 0, 0)
        self.set_color('text')


def _severity_key(severity: str) -> str:
    if not severity:
        return 'low'
    s = severity.lower()
    if 'crit' in s: return 'critical'
    if 'high' in s: return 'high'
    if 'med'  in s: return 'medium'
    return 'low'


def _truncate(text: str, max_len: int = 250) -> str:
    if not text or len(text) <= max_len:
        return text or ''
    chunk = text[:max_len]
    if ' ' in chunk:
        chunk = chunk.rsplit(' ', 1)[0]
    return chunk + '...'


def _priority_label(score: float) -> str:
    if score is None:
        return 'N/A'
    if score >= 80: return 'CRITICAL'
    if score >= 55: return 'HIGH'
    if score >= 30: return 'MEDIUM'
    return 'LOW'


def generate_scan_report(scan_id):
    """Generate PDF report for a completed scan with priority scores."""
    if not scan_id:
        raise ValueError("Scan ID cannot be empty")

    scan = db.session.get(Scan, scan_id)
    if not scan:
        raise ValueError(f"Scan {scan_id} not found")

    if scan.status and scan.status.lower() not in ('completed', 'failed'):
        raise ValueError(f"Cannot generate report for scan in '{scan.status}' status")

    # ── Get and prioritize vulnerabilities ───────────────────────────────────
    vulnerabilities = Vulnerability.query.filter_by(scan_id=scan_id).all()

    # Run prioritization to get proper priority scores
    ranked_vulns = []
    try:
        from ai.prioritization import prioritize_vulnerabilities
        ranked = prioritize_vulnerabilities(vulnerabilities)
        ranked_vulns = ranked  # list of (vuln, score)
    except Exception as e:
        logger.warning("Prioritization failed, using raw vulns: %s", e)
        ranked_vulns = [(v, None) for v in vulnerabilities]

    # Severity counts (case-insensitive)
    severity_counts = {'critical': 0, 'high': 0, 'medium': 0, 'low': 0}
    for v in vulnerabilities:
        severity_counts[_severity_key(v.severity)] += 1

    critical = severity_counts['critical']
    high     = severity_counts['high']
    medium   = severity_counts['medium']
    low      = severity_counts['low']
    total    = len(vulnerabilities)

    # VM info
    vm = None
    if vulnerabilities:
        vm_id = vulnerabilities[0].vm_id
        if vm_id:
            vm = db.session.get(VM, vm_id)

    # ── Build PDF ─────────────────────────────────────────────────────────────
    pdf = ScanReportPDF()
    pdf.set_title(f'Security Scan Report - {scan.target}')
    pdf.set_subject('Security vulnerability scan results')
    pdf.add_page()

    # ── Cover page ────────────────────────────────────────────────────────────
    pdf.set_font('Arial', 'B', 24)
    pdf.set_color('accent')
    pdf.ln(30)
    pdf.cell(0, 15, 'Security Scan Report', 0, 1, 'C')
    pdf.ln(10)

    pdf.set_font('Arial', '', 14)
    pdf.set_color('muted')
    pdf.cell(0, 8, f'Scan ID: {scan.id}', 0, 1, 'C')
    pdf.cell(0, 8, f'Target: {scan.target}', 0, 1, 'C')
    pdf.cell(0, 8, f'Mode: {(scan.mode or "fast").upper()}', 0, 1, 'C')
    date_str = scan.start_time.strftime("%Y-%m-%d %H:%M:%S") if scan.start_time else "N/A"
    pdf.cell(0, 8, f'Date: {date_str}', 0, 1, 'C')
    pdf.cell(0, 8, f'Generated: {datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}', 0, 1, 'C')
    pdf.ln(10)

    # Overall risk indicator on cover
    if critical > 0:
        risk_text  = 'OVERALL RISK: CRITICAL'
        risk_color = 'critical'
    elif high > 0:
        risk_text  = 'OVERALL RISK: HIGH'
        risk_color = 'high'
    elif medium > 0:
        risk_text  = 'OVERALL RISK: MEDIUM'
        risk_color = 'medium'
    else:
        risk_text  = 'OVERALL RISK: LOW'
        risk_color = 'low'

    pdf.set_font('Arial', 'B', 16)
    pdf.set_color(risk_color)
    pdf.cell(0, 12, risk_text, 0, 1, 'C')

    # ── Executive Summary ─────────────────────────────────────────────────────
    pdf.add_page()
    pdf.chapter_title('1. Executive Summary')

    pdf.body_text(
        f'This report presents the results of a {(scan.mode or "fast").upper()} mode '
        f'security vulnerability scan conducted on target "{scan.target}". '
        f'The scan identified {total} vulnerabilities across all assessed assets.'
    )

    # Summary stats table
    pdf.section_title('Vulnerability Summary')
    pdf.stat_row('Total Vulnerabilities:', total)
    pdf.stat_row('Critical:', critical, 'critical')
    pdf.stat_row('High:', high, 'high')
    pdf.stat_row('Medium:', medium, 'medium')
    pdf.stat_row('Low:', low, 'low')
    pdf.ln(3)

    exploitable = sum(1 for v in vulnerabilities if getattr(v, 'exploit_available', False))
    pdf.stat_row('Exploit Available:', exploitable, 'critical' if exploitable > 0 else 'low')
    pdf.ln(5)

    # Risk assessment
    pdf.section_title('Risk Assessment')
    if critical > 0 or high > 0:
        recommendation_summary = (
            'Immediate action required. Critical and high-severity vulnerabilities '
            'pose significant security risks and should be remediated urgently.'
        )
    elif medium > 0:
        recommendation_summary = (
            'Medium-severity vulnerabilities should be addressed in a timely manner '
            'as part of your regular patching cycle.'
        )
    else:
        recommendation_summary = (
            'No critical or high vulnerabilities detected. Continue regular monitoring '
            'and apply low-severity patches during maintenance windows.'
        )

    pdf.set_font('Arial', 'B', 12)
    pdf.set_color(risk_color)
    pdf.cell(0, 8, risk_text, 0, 1)
    pdf.set_font('Arial', '', 11)
    pdf.set_color('text')
    pdf.multi_cell(0, 6, recommendation_summary)
    pdf.ln(5)

    # ── Scan Details ──────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.chapter_title('2. Scan Details')

    pdf.section_title('Target Information')
    pdf.stat_row('Target:', scan.target)
    pdf.stat_row('Scan ID:', scan.id)
    pdf.stat_row('Scan Mode:', (scan.mode or 'fast').upper())
    pdf.stat_row('Status:', scan.status or 'N/A')
    pdf.stat_row(
        'Start Time:',
        scan.start_time.strftime("%Y-%m-%d %H:%M:%S") if scan.start_time else "N/A"
    )
    pdf.stat_row(
        'End Time:',
        scan.end_time.strftime("%Y-%m-%d %H:%M:%S") if scan.end_time else "In progress"
    )

    if scan.start_time and scan.end_time:
        duration = scan.end_time - scan.start_time
        total_seconds = int(duration.total_seconds())
        mins, secs = divmod(total_seconds, 60)
        pdf.stat_row('Duration:', f'{mins}m {secs}s')

    if vm:
        pdf.ln(3)
        pdf.section_title('Asset Information')
        pdf.stat_row('Hostname:', vm.hostname or 'N/A')
        pdf.stat_row('IP Address:', vm.ip_address or 'N/A')
        pdf.stat_row('Operating System:', vm.os or 'Unknown')
        pdf.stat_row('Status:', vm.status or 'N/A')

    pdf.ln(5)

    # ── Priority-Ranked Vulnerabilities ───────────────────────────────────────
    if ranked_vulns:
        pdf.add_page()
        pdf.chapter_title('3. Vulnerability Details (Priority Ranked)')

        pdf.body_text(
            'Vulnerabilities are ranked by composite priority score (0-100) which '
            'combines ML risk score, CVSS, internet exposure, service criticality, '
            'CVE count, and known exploit availability.'
        )

        groups = [
            ('Critical', 'critical'),
            ('High',     'high'),
            ('Medium',   'medium'),
            ('Low',      'low'),
        ]

        for severity_name, severity_key in groups:
            group_vulns = [
                (v, score) for v, score in ranked_vulns
                if _severity_key(getattr(v, 'severity', '')) == severity_key
            ]
            if not group_vulns:
                continue

            pdf.section_title(
                f'{severity_name} Severity ({len(group_vulns)} vulnerabilities)'
            )

            for idx, (vuln, priority_score) in enumerate(group_vulns, 1):
                # Check for page break
                if pdf.get_y() > 250:
                    pdf.add_page()

                pdf.set_font('Arial', 'B', 10)
                pdf.set_color('primary')

                # Vulnerability title
                title = vuln.issue_id or getattr(vuln, 'cve_id', None) or 'Unknown Issue'
                svc_part = ''
                if vuln.service or vuln.port:
                    svc_part = vuln.service or 'service'
                    if vuln.port:
                        svc_part += f' port {vuln.port}'
                    title = f'{title} ({svc_part})'

                pdf.cell(0, 6, f'{idx}. {title}', 0, 1)

                pdf.set_font('Arial', '', 9)
                pdf.set_color('text')

                # Priority score (NEW — from prioritization engine)
                if priority_score is not None:
                    label = _priority_label(priority_score)
                    pdf.cell(0, 5,
                        f'Priority Score: {priority_score:.1f}/100  |  Priority: {label}',
                        0, 1
                    )

                # CVSS score
                cvss = getattr(vuln, 'cvss_score', None)
                if cvss is not None:
                    pdf.cell(0, 5, f'CVSS Score: {cvss}', 0, 1)

                # ML risk score (raw, stored in DB)
                risk_score = getattr(vuln, 'risk_score', None)
                if risk_score is not None:
                    pdf.cell(0, 5, f'ML Risk Score: {risk_score:.2f}/20', 0, 1)

                # Severity
                if vuln.severity:
                    pdf.cell(0, 5, f'Severity: {vuln.severity.upper()}', 0, 1)

                # Service / Port / Version
                if vuln.service:
                    pdf.cell(0, 5, f'Service: {vuln.service}', 0, 1)
                if vuln.port:
                    pdf.cell(0, 5, f'Port: {vuln.port}', 0, 1)
                if vuln.version:
                    pdf.cell(0, 5, f'Version: {vuln.version}', 0, 1)

                # Exploit available flag
                if getattr(vuln, 'exploit_available', False):
                    pdf.set_color('critical')
                    pdf.cell(0, 5, '⚠ Exploit Available', 0, 1)
                    pdf.set_color('text')

                # CVE IDs
                cve_ids = getattr(vuln, 'cve_ids', '') or getattr(vuln, 'cve_id', '')
                if cve_ids:
                    pdf.cell(0, 5, f'CVE IDs: {cve_ids}', 0, 1)

                # Description
                if vuln.description:
                    desc = _truncate(vuln.description, 250)
                    pdf.multi_cell(0, 5, f'Description: {desc}')

                # Remediation notes if present
                remediation = getattr(vuln, 'remediation_notes', '') or ''
                if remediation:
                    pdf.set_color('low')
                    pdf.multi_cell(0, 5, f'Remediation: {_truncate(remediation, 200)}')
                    pdf.set_color('text')

                pdf.ln(4)

    # ── Recommendations ───────────────────────────────────────────────────────
    pdf.add_page()
    pdf.chapter_title('4. Recommendations')

    recs = []
    if critical > 0:
        recs.append(
            f'URGENT: Address all {critical} CRITICAL vulnerabilities immediately. '
            'These pose severe, exploitable security risks.'
        )
    if high > 0:
        recs.append(
            f'HIGH PRIORITY: Remediate {high} HIGH severity vulnerabilities within 7 days.'
        )
    if exploitable > 0:
        recs.append(
            f'EXPLOIT RISK: {exploitable} vulnerabilities have known public exploits. '
            'Patch or mitigate these before others.'
        )
    if medium > 0:
        recs.append(
            f'Plan to fix {medium} MEDIUM severity issues in upcoming maintenance windows.'
        )

    recs.extend([
        'Implement a regular scanning schedule (weekly for production systems).',
        'Keep all systems and software up to date with the latest security patches.',
        'Review and harden network configurations and firewall rules.',
        'Implement network segmentation to limit lateral movement.',
        'Deploy intrusion detection and prevention systems (IDS/IPS).',
        'Enable logging and monitoring for all critical assets.',
        'Conduct security awareness training for all personnel.',
        'Establish a vulnerability management SLA (e.g. Critical: 24h, High: 7d).',
    ])

    for idx, rec in enumerate(recs, 1):
        pdf.set_font('Arial', '', 11)
        pdf.set_color('text')
        pdf.multi_cell(0, 6, f'{idx}. {rec}')
        pdf.ln(3)

    # ── Save PDF ──────────────────────────────────────────────────────────────
    base_dir   = Path(__file__).resolve().parent.parent
    output_dir = base_dir / 'reports' / 'generated'

    try:
        output_dir.mkdir(parents=True, exist_ok=True)
    except OSError as e:
        logger.error('Failed to create reports directory: %s', e)
        raise RuntimeError(f'Failed to create reports directory: {e}')

    filename    = f'scan_{scan_id}_report_{datetime.datetime.now().strftime("%Y%m%d_%H%M%S")}.pdf'
    output_path = output_dir / filename

    pdf.output(str(output_path))
    logger.info("PDF report generated: %s", output_path)
    return str(output_path)